---
# yamllint disable rule:line-length

- name: PostgreSQL High-Availability Cluster Scaling (add replica node)
  hosts: replica
  become: true
  become_method: sudo
  any_errors_fatal: true
  gather_facts: true
  vars_files:
    - vars/main.yml
    - vars/system.yml
    - "vars/{{ ansible_os_family }}.yml"
  vars:
    existing_pgcluster: true

  pre_tasks:
    - name: Checking Linux distribution
      fail:
        msg: "{{ ansible_distribution }} is not supported"
      when: ansible_distribution not in os_valid_distributions

    - name: Checking version of OS Linux
      fail:
        msg: "{{ ansible_distribution_version }} of {{ ansible_distribution }} is not supported"
      when: ansible_distribution_version is version_compare(os_minimum_versions[ansible_distribution], '<')

    - name: Make sure the gnupg package is present
      apt:
        name: gnupg
        state: present
        update_cache: true
      environment: "{{ proxy_env | default({}) }}"
      when: ansible_os_family == "Debian" and installation_method == "repo"
      tags: add_repo, install_packages, install_postgres

    - name: Build a firewall_ports_dynamic_var
      set_fact:
        firewall_ports_dynamic_var: "{{ firewall_ports_dynamic_var |default([]) }} + {{ firewall_allowed_tcp_ports_for[item] }}"
      loop: "{{ hostvars[inventory_hostname].group_names }}"
      when: firewall_enabled_at_boot|bool
      tags: firewall

    - name: Build a firewall_rules_dynamic_var
      set_fact:
        firewall_rules_dynamic_var: "{{ firewall_rules_dynamic_var |default([]) }} + {{ firewall_additional_rules_for[item] }}"
      loop: "{{ hostvars[inventory_hostname].group_names }}"
      when: firewall_enabled_at_boot|bool
      tags: firewall

  roles:
    - role: ansible-role-firewall
      environment: "{{ proxy_env | default({}) }}"
      vars:
        firewall_allowed_tcp_ports: "{{ firewall_ports_dynamic_var|list | unique }}"
        firewall_additional_rules: "{{ firewall_rules_dynamic_var|list | unique }}"
      when: firewall_enabled_at_boot|bool
      tags: firewall

    - role: hostname
    - role: add-repository
    - role: packages
    - role: sudo
    - role: sysctl
    - role: transparent_huge_pages
    - role: pam_limits
    - role: io-scheduler
    - role: locales
    - role: timezone
    - role: ntp
    - role: ssh-keys

    - role: wal-g
      when: wal_g_install|bool

    - role: pgbouncer
      when: install_pgbouncer|bool

    - role: patroni

    - role: vip-manager
      when: not with_haproxy_load_balancing|bool and
            (cluster_vip is defined and cluster_vip | length > 0)

    # finish (info)
    - role: deploy-finish

...
