---

- block:  # install wal-g package from repo
    - name: wal-g | download "wal-g" binary
      get_url:
        url: '{{ item }}'
        dest: /tmp/
        timeout: 60
        validate_certs: false
      loop:
        - '{{ wal_g_package_repo }}'
      environment: '{{ proxy_env | default({}) }}'

    - name: wal-g | extract "wal-g" into /tmp
      unarchive:
        src: '/tmp/{{ wal_g_package_repo | basename }}'
        dest: /tmp/
        remote_src: true

    - name: wal-g | copy "wal-g" binary files to /usr/local/bin/
      copy:
        src: "/tmp/wal-g"
        dest: /usr/local/bin/
        mode: u+x,g+x,o+x
        remote_src: true

  when: installation_method == "repo" and wal_g_package_repo | length > 0
  tags: wal_g_install

- block:  # install wal-g package from file
    - name: wal-g | extract "wal-g" into /tmp
      unarchive:
        src: '{{ wal_g_package_file }}'
        dest: /tmp/

    - name: wal-g | copy "wal-g" binary files to /usr/local/bin/
      copy:
        src: "/tmp/wal-g"
        dest: /usr/local/bin/
        mode: u+x,g+x,o+x
        remote_src: true

  when: installation_method == "file" and wal_g_package_file | length > 0
  tags: wal_g_install

- name: "wal-g | generate conf file {{ postgresql_home_dir }}/.walg.json"
  template:
    src: templates/walg.json.j2
    dest: '{{ postgresql_home_dir }}/.walg.json'
    owner: postgres
    group: postgres
    mode: 0644
  tags: wal_g_install, wal_g_conf

- name: wal-g | copy "wal_g_bootstrap.sh" to /etc/patroni/
  copy:
    src: 'wal_g_bootstrap.sh'
    dest: /etc/patroni/
    owner: postgres
    group: postgres
    mode: 0775
  tags: wal_g_install

...
