---
# yamllint disable rule:comments-indentation

- name: Add extensions to the databases
  become: true
  become_user: postgres
  postgresql_ext:
    db: "{{ item.db }}"
    name: "{{ item.ext }}"
#    login_unix_socket: "{{ postgresql_unix_socket_dir }}"  # ansible v2.8+
    port: "{{ postgresql_port }}"
    state: present
  ignore_errors: true
  loop: "{{ postgresql_extensions | flatten(1) }}"
  when: postgresql_extensions is defined and postgresql_extensions | length > 0
  tags: postgresql_extensions

...
